version: '3'

services:
  ai-bot:
    container_name: ai-bot
    build:
      context: .
    restart: always
    ports:
      - 4500:3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data